name: Build

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Cache PSScriptAnalyzer
        id: cache-psmodules
        uses: actions/cache@v4
        with:
          path: ~/Documents/PowerShell/Modules
          key: psmodules-PSScriptAnalyzer-1.24.0

      - name: Install PSScriptAnalyzer
        if: steps.cache-psmodules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -MinimumVersion 1.24.0

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v6.0.0
        with:
          name: build-output
          path: |
            public
            d/version
            d/*.css
            build/index.html
            build/qiiwexc.bat
            build/qiiwexc.ps1
            build/autounattend-*.xml
