name: Build
run-name: Build (${{ github.ref_name }} - ${{ github.run_attempt }})

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Lint and Test]
    types: [completed]

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: build-output
          path: |
            assets
            d/version
            d/*.css
            build/*.html
            build/*.bat
            build/*.ps1
            build/autounattend-*.xml
