name: Build
run-name: Build (${{ github.ref_name }} - ${{ github.run_attempt }})

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Lint and Test]
    types: [completed]

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        if: ${{ github.ref_name == 'master' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: build-output
          path: |
            assets
            d/version
            d/*.css
            build/index.html
            build/qiiwexc.bat
            build/qiiwexc.ps1
            build/autounattend-*.xml
