name: Build
run-name: Build

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, '.') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: build-output
          path: |
            d/*.bat
            d/*.xml
          retention-days: 90

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          name: ${{ github.event.workflow_run.head_branch }}
          files: |
            d/*.bat
            d/*.xml
