name: Build

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache PSScriptAnalyzer
        id: cache-psmodules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/Documents/PowerShell/Modules
          key: psmodules-PSScriptAnalyzer-1.24.0

      - name: Install PSScriptAnalyzer
        if: steps.cache-psmodules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -RequiredVersion 1.24.0

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-output
          path: |
            public
            d/version
            d/*.css
            build/index.html
            build/qiiwexc.bat
            build/qiiwexc.ps1
            build/autounattend-*.xml
