name: Build
run-name: Build

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Run build
        run: .\build-ci.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: build-output
          path: |
            d/*.bat
            d/*.xml

      - name: Check for tag
        id: check_tag
        run: |
          $tag = git tag --points-at ${{ github.event.workflow_run.head_sha }}
          if ($tag) {
            "tag=$tag" >> $env:GITHUB_OUTPUT
            "is_tag=true" >> $env:GITHUB_OUTPUT
          } else {
            "is_tag=false" >> $env:GITHUB_OUTPUT
          }

      - name: Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        if: steps.check_tag.outputs.is_tag == 'true'
        with:
          tag_name: ${{ steps.check_tag.outputs.tag }}
          name: ${{ steps.check_tag.outputs.tag }}
          generate_release_notes: true
          files: |
            d/*.bat
            d/*.xml
