name: Create a release
run-name: Create a release

permissions:
  contents: write

on:
  workflow_run:
    branches: [master]
    workflows: [Deploy to GitHub Pages]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 100
          fetch-tags: true

      - name: Check for tag
        id: check_tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(git tag --points-at ${{ github.event.workflow_run.head_sha }})
          if [ -z "$tag" ]; then
            echo "No tag found, cancelling workflow"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Check if release exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${{ steps.check_tag.outputs.tag }}"
          if gh release view "$tag" > /dev/null 2>&1; then
            echo "Release $tag already exists, cancelling workflow"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi

      - name: Download build artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          name: deploy-output
          path: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          tag_name: ${{ steps.check_tag.outputs.tag }}
          name: ${{ steps.check_tag.outputs.tag }}
          generate_release_notes: true
          files: |
            qiiwexc.bat
            qiiwexc.ps1
            autounattend-*.xml
